### ISSUE TITLE
Country Code

### ISSUE THREAD

**Issue by nratifainah** [NikKovIos/NKVPhonePicker#11]
Hello, is it possible to get selected Country Code like "RU", "GB", etc?

I tried to make an extension and return
`return self.flagView.currentPresentingCountry.countryCode`

but im getting error  'flagview is inaccessible due to internal protection level'

Thanks

**Comment by NikKovIos** [comment]
Yes, you can get it by
`outputLabel.text = topTextField.currentSelectedCountry?.countryCode`
