### ISSUE TITLE
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

### ISSUE THREAD

**Issue by nratifainah** [NikKovIos/NKVPhonePicker#13]
after updated pods for xcode 9 and I'm getting the error below for NKVPhonePicker.

Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

**Comment by NikKovIos** [comment]
Here is the answer https://github.com/danielgindi/Charts/issues/2816#issuecomment-331375523
Reopen if need.
