### ISSUE TITLE
Obj-c 

### ISSUE THREAD

**Issue by hammoudeh** [NikKovIos/NKVPhonePicker#14]
Is it compatible with obj-c ?

**Comment by NikKovIos** [comment]
Yes, it should be compatible with Objective-C. Write `use_frameworks!` in podfile.
 Also maybe [this](https://stackoverflow.com/a/47751359/5790492) answer would help you if `The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.` would appear.
