### ISSUE TITLE
'characters' is deprecated: Please use String or Substring directly

### ISSUE THREAD

**Issue by rapholivera** [NikKovIos/NKVPhonePicker#17]
![screen shot 2018-02-16 at 12 34 23](https://user-images.githubusercontent.com/19297611/36312463-c58b2d88-1315-11e8-9b98-0cb823525add.png)
![screen shot 2018-02-16 at 12 34 28](https://user-images.githubusercontent.com/19297611/36312465-c9cd2ea0-1315-11e8-9347-dc59659d7919.png)

**Comment by NikKovIos** [comment]
Fixed in https://github.com/NikKovIos/NKVPhonePicker/releases/tag/2.0.0
