### ISSUE TITLE
Force countrycode

### ISSUE THREAD

**Issue by embassem** [NikKovIos/NKVPhonePicker#19]
## General Information

* NKVPhonePicker Version:
1.2.1
* iOS Version(s):
11
* Swift Version:
4
* Device or Simulator:
Device
* Did you check an example:
yes
##  What happened?
there is know way to force country Not to change  
by click  on the  flag  or remove the code text 

## What did you expect to happen?
when delete  old mobile  it may  not delete country code  and  not change the country flag

**Comment by NikKovIos** [comment]
Thanks for the issue. Since there version 2.0.1, i hope you would update your's. Also this feature is not supported now, but feel free to add a PR :)

**Comment by NikKovIos** [comment]
As i understand, you want to make flag fixed (for one language only)?

**Comment by NikKovIos** [comment]
Fixed in https://github.com/NikKovIos/NKVPhonePicker/commit/455dcf9c9db7cb2645890c659cbc3c65ac514026 commit, please check.

**Comment by NikKovIos** [comment]
@embassem any updates?
