### ISSUE TITLE
wrong phone formatting

### ISSUE THREAD

**Issue by alqa-dash** [NikKovIos/NKVPhonePicker#20]
Hi!

If I set customPhoneFormats as "### ## ### ## ##" and start typing phone number, the resulting phone number looks as follows "+374 28123456678901", but when I delete digits up to country code "+374" and try to type phone number again - format applies correctly.

**Comment by NikKovIos** [comment]
Fixed in https://github.com/NikKovIos/NKVPhonePicker/commit/455dcf9c9db7cb2645890c659cbc3c65ac514026 commit, please check.
