### ISSUE TITLE
How can append text programmatically?

### ISSUE THREAD

**Issue by invisible66** [NikKovIos/NKVPhonePicker#22]
## General Information

* NKVPhonePicker Version:
Last version
* iOS Version(s):
11.3.1
* Swift Version:
4.1
* Device or Simulator:
Device
* Did you check an example:
Yes, 
##  What happened?
I am developing a softphone, I have my own numpad. I could not set pressed button value to `NKVPhonePickerTextField` . It's appending first digit only.

     func buttonPressed(digit: String) {   
        var val = txtDialedNumber.text
        val?.append(digit)
        txtDialedNumber.text = val

        // i tried this -> txtDialedNumber.text.append(digit)
     }

**Comment by NikKovIos** [comment]
NKVPhonePicker is just a subclass of the UITextField and all the magic produces here

```swift
extension NKVPhonePickerTextField: UITextFieldDelegate {
    @objc fileprivate func textFieldDidChange() {
        if let newString = self.text, isFlagFixed == false {
            if newString.count == 1 || newString.count == 0 {
                self.setFlag(source: NKVSource(country: Country.empty))
            }
            
            let firstFourLetters = String(newString.prefix(5))
            self.setFlag(source: NKVSource(phoneExtension: firstFourLetters))
        }
    }
}
```
It is a method, that called when .editingChanged.
So you can do whatever you want taking into account the logic of this method. 

Concerning you question i think you should store a string into your model and set the textField text only like textField.text = "textWithAppendedElement"

**Comment by NikKovIos** [comment]
Further discussion will be here https://github.com/NikKovIos/NKVPhonePicker/issues/27

**Comment by Ahyox** [comment]
Hello, you've done a great job with this library. Thank you.

I'm having a good problem inserting text programatically, whenever I add text by using textField.text = "text here" it remove some text.

If I use textField.insertText("text") it give completely different text.

Below is a screenshot to buttress my point. (The last text in the debug is the current selected number)

<img width="736" alt="Screenshot 2020-10-10 at 14 53 53" src="https://user-images.githubusercontent.com/7904501/95656869-14697980-0b09-11eb-99d0-a6bb79396c3a.png">
<img width="765" alt="Screenshot 2020-10-10 at 14 57 35" src="https://user-images.githubusercontent.com/7904501/95656873-17646a00-0b09-11eb-8267-c5dd3c5a2564.png">

Hope to hear from you soon.

**Comment by NikKovIos** [comment]
@Ahyox provide step to reproduce please. Also what you expect and what happening.
