### ISSUE TITLE
Selected search Country did not reflect. Search Dismiss crashed

### ISSUE THREAD

**Issue by sujalBandhara** [NikKovIos/NKVPhonePicker#26]
## General Information

* NKVPhonePicker Version: 2.0.1

* iOS Version(s): 11

* Swift Version: 4.1

* Device or Simulator: Simulator

* Did you check an example: 

##  What happened?
Try to search country from search text field 
Select country 
Selected search Country did not reflect. 

also, App crash when Dismiss Search

## What did you expect to happen?
Selected search country should appear in the text field 
The app should not crash on dismiss

Crash Logs:

2018-06-13 16:19:54.450526+0530 PocketRehab[2300:25819] [Common] _BSMachError: port 1e53b; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2018-06-13 16:19:54.506719+0530 PocketRehab[2300:25819] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modal view controller on itself. Presenting controller is <UISearchController: 0x7feea6635a00>.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112f941e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000112625031 objc_exception_throw + 48
	2   UIKit                               0x0000000110021a95 __78-[UIViewController _presentViewController:withAnimationController:completion:]_block_invoke + 0
	3   UIKit                               0x00000001100242c6 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 99
	4   UIKit                               0x0000000110024958 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
	5   UIKit                               0x000000011002422c -[UIViewController _presentViewController:animated:completion:] + 169
	6   UIKit                               0x0000000110024570 -[UIViewController presentViewController:animated:completion:] + 154
	7   UIKit                               0x0000000110c25bd9 __51-[UISearchController _performAutomaticPresentation]_block_invoke + 330
	8   UIKit                               0x0000000110bc7a29 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 294
	9   UIKit                               0x0000000110bc36d5 -[_UIViewControllerTransitionContext _runAlongsideCompletions] + 132
	10  UIKit                               0x0000000110bc33c4 -[_UIViewControllerTransitionContext completeTransition:] + 118
	11  UIKit                               0x000000010fe754b3 _runAfterCACommitDeferredBlocks + 318
	12  UIKit                               0x000000010fe6471e _cleanUpAfterCAFlushAndRunDeferredBlocks + 388
	13  UIKit                               0x000000010fe92ea5 _afterCACommitHandler + 137
	14  CoreFoundation                      0x0000000112f36607 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	15  CoreFoundation                      0x0000000112f3655e __CFRunLoopDoObservers + 430
	16  CoreFoundation                      0x0000000112f1ab81 __CFRunLoopRun + 1537
	17  CoreFoundation                      0x0000000112f1a30b CFRunLoopRunSpecific + 635
	18  GraphicsServices                    0x0000000119403a73 GSEventRunModal + 62
	19  UIKit                               0x000000010fe6a057 UIApplicationMain + 159
	20  PocketRehab                         0x000000010f157687 main + 55
	21  libdyld.dylib                       0x0000000114bc3955 start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

following link helps me to resolved crash 
https://stackoverflow.com/questions/46917918/ios-uisearchcontroller-crash-application-tried-to-present-modal-view-controller?rq=1&utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by NikKovIos** [comment]
Sorry, i don't have enough time to watch this error right now. Since it an open source, you can try to check it and create a PR. Have a good day 🤓

**Comment by NikKovIos** [comment]
@sujalBandhara @ameerelephant
Please, take the pod from the master branch with latest commit and tell if the bug is resolved
```
pod 'NKVPhonePicker', :git => 'https://github.com/NikKovIos/NKVPhonePicker.git', :branch => 'master'
```

**Comment by NikKovIos** [comment]
Closed due to less of activity. Feel free to reopen.
