### ISSUE TITLE
Changing the alignment of NKVPhonePickerTextField does not change the Flag and the + sign

### ISSUE THREAD

**Issue by Saikedo** [NikKovIos/NKVPhonePicker#29]
When you set an alignment for the NKVPhonePickerTextField to lets say bottom, the phone number correctly aligns to the bottom but the flag and the plus sign seem to always be aligned to center left.

![screen shot 2018-07-24 at 10 15 24 am](https://user-images.githubusercontent.com/19657054/43154831-878e13ce-8f2a-11e8-882f-ee0052a317ef.png)

Is there a way to change this behavior ?

**Comment by NikKovIos** [comment]
You can fix it only if change the frame in code. The frames for the flag and plus calculated manually, so it don't rely on alignment property of the UITextField. 😕

**Comment by NikKovIos** [comment]
Please commit a PR if you would take this problem into account, but this is not hard-needed feature, so i regretfully not going to work at it. Closing the issue.
