### ISSUE TITLE
getting dial code from phone number

### ISSUE THREAD

**Issue by alielephant** [NikKovIos/NKVPhonePicker#31]
Is it possible to get the dial code from the phone number?

The following code will give me the phone number along with the dial code:
`txtPhoneNumber.phoneNumber` 

Is there any way to get the phone number without dial code, and get dial code without phone number?

**Comment by alielephant** [comment]
I use the following code to get the dial code : 
`txtPhoneNumber.code`

Is there is a way to get phone number without the dial code ? 
Currently, I am counting the number of index in dial code and remove it from the `txtPhoneNumber.phoneNumber`

**Comment by NikKovIos** [comment]
Hi) You have a code, you have a whole phone number. Think what to do next )))   
You would need something like:

```swift
let onlyNumber = phoneNumber!.dropFirst(phoneNumber!.count)
```
