### ISSUE TITLE
Could not build Objective-C module 'NKVPhonePicker'

### ISSUE THREAD

**Issue by okdolly** [NikKovIos/NKVPhonePicker#34]
## General Information

* NKVPhonePicker Version:
2.0.1
* iOS Version(s):
10.13.6
* Swift Version:
4.0
* Device or Simulator:
Phone XR
* Did you check an example:
Yes
##  What happened?

Could not build Objective-C module 'NKVPhonePicker'

**Comment by NikKovIos** [comment]
I've tried to build Example project on iPhone XR simulator and it works well. However, i use the version 2.0.3 of this pod. Try to update and test again.

**Comment by NikKovIos** [comment]
Closed due to less of activity. Feel free to reopen.

**Comment by iKambad3618** [comment]
Hello nikkovlos

I am trying to use your library in objective c but I am not able to access such below listed properties
@property (weak, nonatomic) IBOutlet NKVPhonePickerTextField *txtPhoneNumber;
txtPhoneNumber. favoriteCountriesLocaleIdentifiers = @[@"US",@"NG"];

Giving error : Property 'favoriteCountriesLocaleIdentifiers' not found on object of type 'NKVPhonePickerTextField *

**Comment by NikKovIos** [comment]
@iKambad3618 hi, sorry, right now i don't have time to check this. Please check it  for yourself and submit a pr.
