### ISSUE TITLE
NKVPhonePickerTextField.swift twice in project

### ISSUE THREAD

**Issue by ARGAMX** [NikKovIos/NKVPhonePicker#37]
## General Information

* NKVPhonePicker Version:
2.0.1

##  What happened?

>CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
    cd /Users/vsts/agent/2.140.2/work/1/s/Pods
    export DEVELOPER_DIR=/Applications/Xcode_9.4.1.app/Contents/Developer
    export PATH="/Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode_9.4.1.app/Contents/Developer/usr/bin:/Library/Frameworks/Mono.framework/Versions/4/bin:/usr/local/bin:/usr/local/sbin:/Users/vsts/bin:/Users/vsts/.yarn/bin:/usr/local/go/bin:/Users/vsts/Library/Android/sdk/tools:/Users/vsts/Library/Android/sdk/platform-tools:/Users/vsts/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vsts/.azcopy"
    export SDKROOT=/Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk
    >/Applications/Xcode_9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name NKVPhonePicker -O -whole-module-optimization -D COCOAPODS -suppress-warnings -sdk /Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk -target armv7-apple-ios9.0 -g -module-cache-path /Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -embed-bitcode -swift-version 3 -I /Users/vsts/Library/Developer/Xcode/DerivedData/Robomed-hkguzfozedxpeactgxnakujerabq/Build/Intermediates.noindex/ArchiveIntermediates/Robomed/BuildProductsPath/Release-iphoneos/NKVPhonePicker -F /Users/vsts/Library/Developer/Xcode/DerivedData/Robomed-hkguzfozedxpeactgxnakujerabq/Build/Intermediates.noindex/ArchiveIntermediates/Robomed/BuildProductsPath/Release-iphoneos/NKVPhonePicker -c -num-threads 4 /Users/vsts/agent/2.140.2/work/1/s/Pods/NKVPhonePicker/Sources/Main/CountriesViewController.swift /Users/v...
<unknown>:0: error: filename "NKVPhonePickerTextField.swift" used twice: 
'/Users/vsts/agent/2.140.2/work/1/s/Pods/NKVPhonePicker/Sources/Main/NKVPhonePickerTextField.swift' and 
'/Users/vsts/agent/2.140.2/work/1/s/Pods/NKVPhonePicker/Sources/Views/NKVPhonePickerTextField.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
Command /Applications/Xcode_9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

there double files NKVPhonePickerTextField in project.

> '/Users/vsts/agent/2.140.2/work/1/s/Pods/NKVPhonePicker/Sources/Main/NKVPhonePickerTextField.swift'
> '/Users/vsts/agent/2.140.2/work/1/s/Pods/NKVPhonePicker/Sources/Views/NKVPhonePickerTextField.swift'

**Comment by ARGAMX** [comment]
Pull request with fix:
https://github.com/NikKovIos/NKVPhonePicker/pull/36

**Comment by NikKovIos** [comment]
Very interesting! Thanks a ton for your help! 👏🏻
