### ISSUE TITLE
Pod files are not updated

### ISSUE THREAD

**Issue by FadyDerias** [NikKovIos/NKVPhonePicker#4]
Hello, first of all thank you for such an awesome library.

Just installed it via cocoapods as instructed in your README.md file. Unfortunately when implementing it, the countries view controller doesn't get presented. When comparing files downloaded via cocoapods with the files included in the provided example, they're not the same.

Thanks!

**Comment by NikKovIos** [comment]
Thanks;) 

Please firstly try to make a pod update. If it wouldn't help,  write a direct link to this repo in Podfile pod 'NKVPhonePicker', :git => "https://github.com/NikKovIos/NKVPhonePicker.git"
and tell me if it would help.

**Comment by FadyDerias** [comment]
Using the direct link did do the job.
Thank you.

**Comment by NikKovIos** [comment]
Added a new release with tag 1.1.0
Use `pod update`
