### ISSUE TITLE
How to customize NKVFlagView ? 

### ISSUE THREAD

**Issue by JhonnyTawk** [NikKovIos/NKVPhonePicker#40]

**Comment by JhonnyTawk** [comment]
I want to add a drop-down arrow next to the flag and change the spacing between the country code extension and the phone number

**Comment by NikKovIos** [comment]
Flag view is just a view (look at the code). It not allowed by api to customize it in a such way.

**Comment by JhonnyTawk** [comment]
do you have any version with a Xib or Storyboard?

**Comment by NikKovIos** [comment]
Nope
