### ISSUE TITLE
How to open NKVFlagView when user click on textField

### ISSUE THREAD

**Issue by shaharukhs** [NikKovIos/NKVPhonePicker#41]
## General Information

* NKVPhonePicker Version: NA

* iOS Version(s): 12.0

* Swift Version: 4.2

* Device or Simulator: Both

* Did you check an example: Yes

##  What happened?
When user click on textField, keyboard was showing but I want to show flagView using MKFlagView

## What did you expect to happen?
I want to show flagView using MKFlagView when click on textFIeld and update textFIeld text with selected country name.

**Comment by NikKovIos** [comment]
First write what version you use.
Next what is MKFlagView?
You need functional that is not rely to main pod needs. You can get the code and implement what needed with it.
