### ISSUE TITLE
PlaceHolder not shown

### ISSUE THREAD

**Issue by tjsingh04** [NikKovIos/NKVPhonePicker#44]
##  What happened?

Placeholder is not shown even if set it programatically or from storyboard

## What did you expect to happen?

Placeholder should shown in text feild

**Comment by NikKovIos** [comment]
@tjsingh04 Did you check the example project?

**Comment by tjsingh04** [comment]
yes i was checked , i think the problem is pre fill text of country code in the textfield, when i remove country code then it show the placeholder but i need it even if country code is there.

**Comment by NikKovIos** [comment]
Place your code or project here.

**Comment by tjsingh04** [comment]
set `NKVPhonePickerTextField` directly from storyboard and create its outlet  shown as below 

   **@IBOutlet weak var phoneTF: NKVPhonePickerTextField!**

and in viewDidLoad is have use below code

        **phoneTF.phonePickerDelegate = self
        phoneTF.placeholder = "Phone Number"
        phoneTF.flagInsets = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 0)
        phoneTF.layer.cornerRadius = 10**

**Comment by tjsingh04** [comment]
you can also check in your sample project as well. placeholder only shows when remove country code from it. but i need it with country code if you can help
![Simulator Screen Shot - iPhone Xʀ - 2019-05-09 at 12 30 54](https://user-images.githubusercontent.com/47655390/57433546-647a4780-7256-11e9-9c1a-43daf71bd4e7.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-05-09 at 12 31 01](https://user-images.githubusercontent.com/47655390/57433547-647a4780-7256-11e9-8731-7d7c0c1e3baa.png)

**Comment by NikKovIos** [comment]
Hmm, the plus is too close to flag also. What phone model is it?
Fix your message markdown pls.

**Comment by NikKovIos** [comment]
Sorry, but the textField is using a standard placeholder and i don't see how to easily change its behaviour.

However you can set a little hack like:

```swift
textField.countryPickerDelegate = self

extension ViewController: CountriesViewControllerDelegate {
    func countriesViewController(_ sender: CountriesViewController, didSelectCountry country: Country) {
        print("✳️ Did select country: \(country)")
        bottomTextField.placeholder = country.phoneExtension
    }
}
```

Also tell what you exactly want to achieve?

**Comment by tjsingh04** [comment]
i just want to show place holder just like my second screenshoot, but it only show when i remove whole text from textfield i.e when remove country code, means place holder is not shown with country code added in textfield, it shows when i remove country code.

i want to show place holder with country code added in textfield. do you get my point?

**Comment by NikKovIos** [comment]
So i think its can not be done, only with hack, that i produced.

вт, 14 мая 2019 г., 11:11 tjsingh04 notifications@github.com:

**Comment by tjsingh04** [comment]
yes i think so, is there any other hack for it

**Comment by NikKovIos** [comment]
Try to find yourself, you have a code)

вт, 14 мая 2019 г. в 12:21, tjsingh04 <notifications@github.com>:

**Comment by tjsingh04** [comment]
okay Thanks Brother
