### ISSUE TITLE
Country object doesn't get updated when changing code from text field.

### ISSUE THREAD

**Issue by FadyDerias** [NikKovIos/NKVPhonePicker#5]
When I start the app, I set the default country for the NKVPhonePickerTextField using the Locale.regionCode, to display the equivalent code and flag.

If the user changes the default set country by deleting the default code and replacing it with another code, the country object associated with the NKVPhonePickerTextField doesn't get updated and when navigating to the countries view controller, the old country (the default one) is still set by a checkmark.

**Comment by NikKovIos** [comment]
Sorry, but i can't understand how to reproduce it. 
Could you please write step by step how to do it?
Like:
1) When app starts i do 'phonePicker.favoriteCountries = "EN"' 
2) ...

**Comment by FadyDerias** [comment]
1)  when the app starts, I create Country object as the following, 
let country = Country.countryBy(countryCode: "EG") [Egypt]

2)  Setting the code and flag in the NKVPhonePickerTextField text field
      NKVPhonePickerTextField.setCode(country: country)
      NKVPhonePickerTextField.setFlag(country: country)

At this point everything is ok, I present the view controller and the NKVPhonePickerTextField flag and code are set as described above, and I can get all the equivalent data from the NKVPhonePickerTextField country object.

If I remove the code in the text field, and enter a new code .. for eg. +1 for Canada, the country object of the NKVPhonePickerTextField is still set to "Egypt", and not updated to "Canada". In addition if I display the countries view controller, the selected country is still set to Egypt.

**Comment by FadyDerias** [comment]
Any updates ? :)

**Comment by NikKovIos** [comment]
Sorry, I tried to reproduce it, but can't. In example project in `viewDidLoad` i did:
```
let country = Country.countryBy(countryCode: "EG")
topTextField.setCode(country: country)
topTextField.setFlag(country: country)
```

But after compiling, everything still remains functional as it should.
