### ISSUE TITLE
Can you help me ?

### ISSUE THREAD

**Issue by hong0595** [NikKovIos/NKVPhonePicker#8]
@IBOutlet public weak var phonePickerDelegate: UIViewController?
你好
请问这个phonePickerDelegate如何创建？

how are you
How to create this phonePickerDelegate ?

**Comment by NikKovIos** [comment]
Hello)
Look at example project

![nkvphonepicker_exampleviewcontroller_swift_at_master_ _nikkovios_nkvphonepicker](https://user-images.githubusercontent.com/16647690/30323070-71d5c490-97c4-11e7-84a0-0dc3bd0d5812.jpg)

**Comment by hong0595** [comment]
class ViewController: UIViewController {

    @IBOutlet var topTextField: NKVPhonePickerTextField!
    override func viewDidLoad() {
        super.viewDidLoad()
        topTextField.phonePickerDelegate = self//////////-----------------------------**here**
        topTextField.favoriteCountriesLocaleIdentifiers = ["RU", "ER", "JM"]
        let country = Country.countryBy(countryCode: "EG")
        topTextField.currentSelectedCountry = country
        topTextField.customPhoneFormats = ["RU" : "# ### ### ## ##",
                                           "GB": "## #### #########"]
    }

Compile failed
Thread 1:EXC_BAD_ACCESS(code=1,address=0x0

**Comment by NikKovIos** [comment]
I just downloaded a project, compiled an example and everything works well. Check your code please.

**Comment by hong0595** [comment]
OK, I'll study it again. Thank you very much for your answer

**Comment by hong0595** [comment]
![error001](https://user-images.githubusercontent.com/21987345/30329888-3f1197ae-9806-11e7-9e1a-9e7925b8d2e1.png)
![error002](https://user-images.githubusercontent.com/21987345/30329889-3f525118-9806-11e7-8700-a8b769c7aa59.png)

I'm sorry,
Please take a look at me again.

**Comment by NikKovIos** [comment]
Check tge the class of the text field in Storyboard

**Comment by hong0595** [comment]
![2017-09-13 08 29 27](https://user-images.githubusercontent.com/21987345/30354245-05e5527e-985e-11e7-9fb8-7ba92c282015.png)
![2017-09-13 08 30 30](https://user-images.githubusercontent.com/21987345/30354246-061be226-985e-11e7-8488-1217a0adf7d4.png)

Good,Very good.   ^_^   Thank you very much ^_^
