### ISSUE TITLE
Wrong Flags

### ISSUE THREAD

**Issue by alexionut** [NikKovIos/NKVPhonePicker#9]
Hello, there's a problem with the country selection. If i select United States, it shows me the Canada Flag. The selection for UK also shows wrong flag.

**Comment by OlexandrRutenko** [comment]
@NikKovIos  Hi, any news on this issue?

**Comment by NikKovIos** [comment]
Hello, not yet, sorry. You can try to manage it by yourself and submit a PR then.

**Comment by OlexandrRutenko** [comment]
@NikKovIos Hi, created PR. [https://github.com/NikKovIos/NKVPhonePicker/pull/12](url)

**Comment by OlexandrRutenko** [comment]
@NikKovIos Hi, created PR.

**Comment by NikKovIos** [comment]
Thank you. I'll check it asap.

**Comment by NikKovIos** [comment]
Thanks for your contribution. Merged in https://github.com/NikKovIos/NKVPhonePicker/pull/12
